environment_version: 1
credentials:
- type: aws
  id: dYkkk5ioQ0ppSk
  description: AIND data S3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: CKt36k5mbd4lCh
  description: CO Token
  key: API_KEY
  secret: API_SECRET
